In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/wine-quality/winequalityN.csv
/kaggle/input/diabetes-dataset/diabetes2.csv
/kaggle/input/wine-tasting/winemag-data-130k-v2.csv
/kaggle/input/video-game-sales-2024/vgchartz-2024.csv
/kaggle/input/real-estate-price-prediction/Real estate.csv
/kaggle/input/national-flowers/flowerdataset/test/Orchid/1d043ac951.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/2eaca1c694.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/002c100a56.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/2e2d816ec1.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/4ccad8166c.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/1af420b606.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/1cf162c110.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/1ebc5e49c4.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/1a3d96a2e7.jpg
/kaggle/input/national-flowers/flowerdataset/test/Orchid/2d4ee50c2f.jpg
/kaggle/input/national-flo

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/kaggle/input/gender-by-name/name_gender_dataset.csv')
df = df.dropna(axis=1)
df.shape

(147269, 4)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147269 entries, 0 to 147268
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Name         147269 non-null  object 
 1   Gender       147269 non-null  object 
 2   Count        147269 non-null  int64  
 3   Probability  147269 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 4.5+ MB


In [4]:
df.isnull().sum()

Name           0
Gender         0
Count          0
Probability    0
dtype: int64

As we can see, in some columns about 70-80%  of the data is missing

In [5]:
df.columns

Index(['Name', 'Gender', 'Count', 'Probability'], dtype='object')

In [6]:
df.head()

Name Gender    Count  Probability
0    James      M  5304407     0.014517
1     John      M  5260831     0.014398
2   Robert      M  4970386     0.013603
3  Michael      M  4579950     0.012534
4  William      M  4226608     0.011567

In [7]:
df["Gender"] = df["Gender"].map({"M":1,"F":0})

In [8]:
df.head()

Name  Gender    Count  Probability
0    James       1  5304407     0.014517
1     John       1  5260831     0.014398
2   Robert       1  4970386     0.013603
3  Michael       1  4579950     0.012534
4  William       1  4226608     0.011567

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["Name"] = encoder.fit_transform(df["Name"])

In [10]:
df.head()

Name  Gender    Count  Probability
0   52308       1  5304407     0.014517
1   57879       1  5260831     0.014398
2  102035       1  4970386     0.013603
3   84621       1  4579950     0.012534
4  128418       1  4226608     0.011567

In [11]:
from sklearn.model_selection import train_test_split

x=df.drop('Gender',axis=1)
y=df['Gender']
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.25, random_state=42)

In [12]:
x_train.head()

Name  Count   Probability
137531   40387      1  2.736740e-09
78464    49567     13  3.557760e-08
144357  106359      1  2.736740e-09
18893    71543    467  1.278060e-06
96545     4896      5  1.368370e-08

# **LOGISTIC REGRESSION**

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import metrics

LGR_Classifier = LogisticRegression(n_jobs=-1, random_state=0)
LGR_Classifier.fit(x_train, y_train)
predictions = LGR_Classifier.predict(x_test)
accuracy_lr = accuracy_score(y_test, predictions)

print("Model Accuracy : {}".format(accuracy_lr))

confusion_matrix = metrics.confusion_matrix(y_test, predictions)
print("Confusion matrix:" "\n", confusion_matrix)

Model Accuracy : 0.6107882014232169
Confusion matrix:
 [[22468    37]
 [14293    20]]


# **SVM**

In [14]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import classification_report


svc_clf = LinearSVC()
svc_clf.fit(x_train, y_train)
predictions = svc_clf.predict(x_test)
accuracy_svm = accuracy_score(y_test,predictions)
print(accuracy_svm)
confusion_matrix = metrics.confusion_matrix(y_test, predictions)
print("Confusion matrix:" "\n", confusion_matrix)

0.6110054864468466
Confusion matrix:
 [[22496     9]
 [14313     0]]


/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


# **DECISION TREE**

In [15]:
# DECISION TREE CLASSIFIER
from sklearn.tree import DecisionTreeClassifier

deccision_classifier = DecisionTreeClassifier()
deccision_classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
# accuracy
# confusion matrix
predictions = deccision_classifier.predict(x_test)
accuracy_dt = metrics.accuracy_score(y_test, predictions)
confusion_matrix = metrics.confusion_matrix(y_test,predictions)

print ("Decision Classifier Model Accuracy:" "\n", accuracy_dt)
print("Decision Classifier Model Confusion matrix:" "\n", confusion_matrix)

Decision Classifier Model Accuracy:
 0.5990004888913032
Decision Classifier Model Confusion matrix:
 [[15033  7472]
 [ 7292  7021]]
